### ISSUE TITLE
Question related to the schematic

### ISSUE THREAD

**Issue by Riktastic** [morcibacsi/arduino_tss463_van#3]
Hi Peter,

I have been following your project for a while now. And was interested in recreating the circuit. I have opened up an old replacement Sagem PP-T40 clock (the one the can be found in Peugeot 206 from 2003). In it I found the TSS461C and the Alcatel 2840 (mine is designated as: 0217 REMQ. Is it possible to use these chips together? Or do I have to look for a TJA1040?

PS: Is Y1 a resonator or a oscillator?

Kind regards, 

Rik

**Comment by morcibacsi** [comment]
Hi,

You can either use the Alcatel 2840 based circuit as described here: https://github.com/morcibacsi/arduino_tss463_van#tss463c--remq0339-van-line-driver

Or a MCP2551/TJA1040/TJA1050 based circuit from here: https://github.com/morcibacsi/arduino_tss463_van#tss463c--mcp2551-can-transceiver

I prefer using CAN transceivers instead of the Alcatel 2840 as they are easier to obtain.

The Y1 is a 8 MHz crystal oscillator.

Here you can take a look on the schematics and a PCB I made for the TSS463 with an MCP2551: https://github.com/morcibacsi/PSAVanCanBridgeHW/tree/v1.4

**Comment by Riktastic** [comment]
Hi Peter,

 thanks for your help. Sadly the TJA1040 is not to be found for sale. I have ordered the TSS463C, the MCP2551 and an additional ESP32 WROOM development kit (which is included in the new users deal) for a total of 8 euro's from AliExpress. It seems to be a great deal.  I haven't received the chips, can't vouch for them. For now this issue can be closed.


For additional lurkers: I'm not willing to let you become my parts supplier. 2 Chinese sellers have used LinkedIn to reach out to me. I do not want you to become my TJA1040 and PCB supplier. This is a personal project, I do not want to profit of this, I do not want to buy anything from you nor do I want you to violate my privacy.

Kind regards,

Rik
